.gitignore
README.md
backend.tf
control_plane.tf
main.tf
output.tf
provider.tf
security_groups.tf
templates/ignition.tmpl
variables.tf
worker.tf

See https://github.com/appuio/openshift4-docs/pull/25

Initial Implementation

---

.github/workflows/test.yaml
backend.tf
modules/node-group/providers.tf
provider.tf

Lint Terraform using:
* `terraform fmt -check -recursive`
* `terraform init && terraform validate`

Add GitHub action to lint Terraform for PRs

---

README.md
modules/node-group/main.tf
modules/node-group/templates/zero_storagepool.service.tmpl
modules/node-group/variables.tf
security_groups.tf
storage.tf
variables.tf

This PR
* Add support for provisioning storage nodes
* Sets up security group rules to run Ceph over the host network.
* Adds a systemd unit on the storage nodes to zero the storagepool partition on first boot

Add support for provisioning storage nodes

---

files/register-server.sh

Backport from https://github.com/appuio/terraform-openshift4-cloudscale/pull/19

Fail register-server on errors

---

.github/workflows/release.yaml

Prepares for a v1.0.0 release, to match with https://github.com/appuio/terraform-openshift4-cloudscale

Add release GH workflow

---

README.md
provider.tf
variables.tf
worker.tf

This PR introduces support for additional worker groups via variable `additional_worker_groups`
Closes #15

Implement support for additional worker groups

---

variables.tf

Relates: APPU-3401
Closes #21 

Fix validation of `additional_worker_groups.count` to allow 0

---

renovate.json

Update renovate config to set "dependency" label on PRs

---

lb.tf
templates/hieradata.yaml.tmpl
variables.tf

Allow passing team for LBaaS

---

lb.tf

Set puppet environment to `AppuioLbaas`

---

lb.tf

Ignore changes in LB user-data after creation

---

README.md
lb.tf
variables.tf

Add support for enabling PROXY protocol on the LBs

---

README.md
lb.tf
variables.tf

Add support for attaching additional private networks to LBs

---

README.md
variables.tf
worker.tf

Add suppport for configuring additional security groups on worker nodes

---

lb.tf

Add suppport for configuring additional affinity groups on load balancer

---

control_plane.tf

They are no longer required for OCP4.4+, according to https://access.redhat.com/solutions/5309701

Remove the etcd SRV records

---

variables.tf

Fix variable description for `additional_lb_networks`

---

modules/node-group/providers.tf

Update minimum required Terraform version to 1.3.0 in `node-group` module

---

main.tf

Use `exoscale_domain.<name>.id` to associate `exoscale_domain_record` resources with their domain

---

modules/node-group/providers.tf
provider.tf

Factored out from #60, replaces #50

Pin Exoscale Terraform provider version to 0.41.0

---

variables.tf

https://ticket.vshn.net/browse/OCP-626

Set default infra node count to 4 to adjust for new default logging.

---

.github/workflows/auto-release.yaml
.github/workflows/release.yaml

This allows us to create new releases of the module by labeling PRs with `bump:patch`, `bump:minor` or `bump:major`

Configure `projectsyn/pr-label-tag-action`
