appuio/terraform-openshift4-exoscale

infra.tf
security_groups.tf
variables.tf

Infra nodes are special compute nodes that only accept infrastructure services, e.g. router, monitoring etc.

Add infra-nodes to the cluster

---

output.tf

The delegation records don't need to contain the full delegated domain, only the cluster's subdomain in the zone.

Adjust NS records output

---

files/keepalived-notify-script
lb.tf
templates/floaty.yaml.tmpl
templates/keepalived.conf.tmpl

* replaces occurrences of `Ursula` with `Floaty`
* Downloads a tagged public release from GitHub (instead from bootstrap bucket)

Use open-source version of Ursula (Floaty)

---

files/commit-hieradata.sh

Previously, we only set the branch to track origin/master when actually pushing changes. However, this breaks subsequent terraform runs if there aren't any changes when we first clone the repository.

Fix commit-hieradata.sh to always set branch to track origin/master

---

modules/node-group/variables.tf

Product documentation: https://products.docs.vshn.ch/products/appuio/managed/ocp4_exoscale.html#_default_configuration_minimum_requirements
Also throw a validation error when users try to create nodes with less than 120GB disk, as that's the minimum supported disk size for OCP4, cf. the [OCP4 documentation].
[OCP4 documentation]: https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal

Configure default node disk size to match product description

---

lb.tf

There's no reason to keep the refresh trigger when the shell script is changed for the `register_lb` resource.
This only leads to unnecessary (and potentially dangerous) changes for already provisioned clusters. The only reason a productive cluster needs to refresh the `register_lb` resource is when the LB names change and the new LBs need to be registered at VSHN.

Disable register_lb refresh trigger when shell script changes

---

README.md
bootstrap.tf
control_plane.tf
infra.tf
modules/node-group/main.tf
modules/node-group/variables.tf
storage.tf
variables.tf
worker.tf

This PR introduces variables to control the size of all node disks.
The PR introduces a variable `root_disk_size` which can be used to configure the size of the root disk of all nodes and a variable `worker_data_disk_size` which can be used to configure an additional data partition on worker nodes. Field `data_disk_size` for entries in `additional_worker_groups` can be used to configure a data partition on additional worker nodes.
**TODO**

Add support for configuring node disk sizes

---

README.md
control_plane.tf
infra.tf
modules/node-group/main.tf
modules/node-group/variables.tf
storage.tf
variables.tf
worker.tf

This allows users to configure pre-existing affinity groups for all cluster VMs (except the bootstrap node). This can be useful for example when wanting to deploy Exoscale VMs on dedicated VM hosts.

Add support for configuring additional affinity group IDs

---

files/commit-hieradata.sh
lb.tf

The `commit-hieradata.sh` script previously had hard-coded location `/tf/.mr_url.txt` to write the URL of the hieradata MR, if any.
This doesn't work in GitLab CI, as the directory structure looks different to the structure we have during cluster setup.
This commit extends the `commit-hieradata.sh` script to take the full path to the `.mr_url.txt` file as a second parameter on the command line and updates the Terraform code to provide the path to the script.
With this change, we can use Terraform's `${path.cwd}` to always create the `.mr_url.txt` file in Terraform's working directory.

Provide location for MR URL file to commit script

---

README.md
variables.tf
worker.tf

Each additional worker group has the possibility to be assigned to a special affinity group
so Exoscale can shedule them on dedicated hardware.

Add support for configuring additional affinity groups in `additional_worker_groups`

---

modules/node-group/templates/zero_storagepool.service.tmpl

With ocp 4.8 there seems to be a slight change in systemd service dependencies. This will cause our zero storagepool service to not start, which will further block kubelet and prevent the storage node to start.

Update zero_storagepool service to start on 4.8

---

README.md
bootstrap.tf
control_plane.tf
infra.tf
lb.tf
main.tf
modules/node-group/main.tf
modules/node-group/variables.tf
output.tf
storage.tf
variables.tf
worker.tf

The new variable allows setups where the cluster domain shouldn't contain the cluster id. This is required for the documented DNS scheme for APPUiO Cloud (cf. [APPUiO Cloud DNS scheme](https://kb.vshn.ch/appuio-cloud/references/dns-naming-scheme.html) vs [APPUiO Managed OCP4 DNS scheme](https://kb.vshn.ch/oc4/explanations/dns_scheme.html)).

Introduce separate variable `cluster_name`

---

bootstrap.tf
infra.tf

Since we've switched to the VSHN Puppet-managed LBs, we don't need the `api-member` and `router-member` DNS records anymore. 
Factored out from #60 

Remove unused DNS records

---

variables.tf

I've encountered errors like reproduced below while testing the state migration for #60.
```
│   on .terraform/modules/cluster/variables.tf line 164, in variable "additional_worker_groups":
│  164:       (v.state == null || lower(v.state) == "running" || lower(v.state) == "stopped")
│     ├────────────────
│     │ v.state is null
│
│ Invalid value for "str" parameter: argument must not be null.
```
Since Terraform boolean operators don't short-circuit, we should use the ternary operator form to perform the validation anyway (we already do this for the disk size parameter). Currently the old approach works because apparently you can compare a string to `null`.

Fix validation logic for `additional_node_groups.*.state`

---

bootstrap.tf
control_plane.tf
infra.tf
main.tf
modules/node-group/main.tf
modules/node-group/output.tf
modules/node-group/variables.tf
security_groups.tf
storage.tf
variables.tf
worker.tf

Closes #59  
This PR requires that the Terraform state of existing clusters is updated manually, please see https://github.com/appuio/component-openshift4-terraform/pull/61 for a Python script which performs the required state migrations.
I've tested both provisioning resources using the new module version and the state migration for resources initially setup with an old module version.

Remove all uses of deprecated Exoscale Terraform resources

---

README.md
control_plane.tf
infra.tf
lb.tf
modules/node-group/main.tf
modules/node-group/variables.tf
storage.tf
variables.tf
worker.tf

Follow-up to #59. When upgrading the Exoscale Terraform provider, we assumed that we can still pass arbitrary affinity group IDs to instances through `anti_affinity_group_ids`, but that parameter has been changed to only accept anti-affinity groups, while there's a new parameter `deploy_target_id` for other affinity group IDs, such as the one necessary to schedule instances on dedicated hypervisors.

Add support for configuring deployment target ID

---

lb.tf
security_groups.tf

By using security group names across the module boundary, we triggered a bug in the Terraform Exoscale provider which results in inconsistent final plans during the initial `terraform apply`.
This commit updates the LB module to v4.2.0 (which includes https://github.com/appuio/terraform-modules/pull/39) and updates the surrounding Terraform to use security group IDs directly.

Switch LB module security group inputs and outputs to IDs

---

modules/node-group/main.tf

We don't manage EIP attachments on cluster instances with Terraform. Ignore changes to the `elastic_ip_ids` field during `terraform plan` / `terraform apply` to not remove attachments managed outside Terraform.

Ignore Elastic IPs attached to compute instances

---

README.md
lb.tf
modules/node-group/providers.tf
provider.tf
variables.tf

Exoscale's new IAM API (v3) isn't yet supported by the Terraform module, so we switch back to a user-provided IAM key for Floaty
This reverts #69 (commit c6938673f029a3cacebf57a555e05f10f385a38d), reversing changes made to 10e07d48fe8de339e2a6084b8e419763c1aeda49.
This PR also updates the Exoscale Terraform provider to v0.50.0, since we've updated the provider in the vshn-lbaas-exoscale module as well.
See https://github.com/appuio/terraform-modules/releases/tag/v5.0.0
Replaces #81 #76 

Switch back to user-provided IAM key for Floaty

---

bootstrap.tf
control_plane.tf
infra.tf
main.tf
storage.tf
worker.tf

The exoscale_compute_template data source has been deprecated in favor of the exoscale_template data source.
With this change, the Terraform module doesn't use any "compute-legacy" API endpoints anymore, which makes working with IAM v3 roles a bit easier.
Follow-up to #80 

Switch to new `exoscale_template` data source

---

lb.tf
variables.tf

This is a breaking change for clusters that were setup with or upgraded to v3 of the Terraform module because migrating to the new Terraform-managed Floaty credentials will require manual steps to ensure that the migration takes place without outages. We'll provide detailed instructions for the upgrade in the openshift4-terraform Commodore component.
Replaces #90 

Manage Floaty credentials in Terraform via vshn-lbaas-exoscale v6.0.0

---

security_groups.tf

We remove the SSH access from anywhere for the cluster VMs by updating the `all_machines` security group to only allow SSH from other machines in the `all_machines` security group.
This PR requires https://github.com/appuio/terraform-modules/pull/51 in order to ensure that the LBs remain accessible from anywhere via SSH and can act as SSH jumphosts for SSH access to the cluster VMs.
Resolves #78 

Restrict SSH access to cluster VMs

---

modules/node-group/main.tf
modules/node-group/variables.tf
variables.tf

RedHat lowered requirements for OpenShift node root disk size to 100Gi.

Change default root disk size to 100Gi

---

control_plane.tf
variables.tf

Support setting instance_type for master nodes

---

control_plane.tf
infra.tf
modules/node-group/main.tf
modules/node-group/variables.tf
storage.tf
variables.tf
worker.tf

A new variable affinity_group_capacity defines the capacity of an affinity group.

Support creating multiple affinit groups

---

lb.tf
variables.tf

This is necessary to open the additional ports when using the additional TCP port mappings feature of the Puppet-managed LBs.

Introduce new optional variable to attach additional security groups to the LBs

---

README.md
control_plane.tf
infra.tf
modules/node-group/main.tf
modules/node-group/output.tf
modules/node-group/variables.tf
security_groups.tf
storage.tf
worker.tf

This PR introduces new variable `use_instancepools` which defaults to `true`. When set to `true`, the module provisions Exoscale instance pools for the infra and worker nodes (including any additional worker nodes).
Additionally, the module provisions a security group which allows traffic from anywhere to the nodeport range and which is attached to all worker nodes when `use_instancepools=true`.
We currently never provision instance pools for the control plane and storage nodes, since there's no clear benefit and day 2 operations are simpler when we can directly modify the existing control plane or storage VMs instead of always having to replace them after modifying instance type or disk size or similar in the instancepool.
`bug`, `enhancement`, `documentation`, `change`, `breaking`, …

Use instance pools for infra and worker node groups

---

modules/node-group/main.tf

Fixes cluster bootstrap in instancepool mode, follow-up to #98 

Only try to create instancepool when `node_count > 0`

---

README.md
infra.tf
variables.tf

We've realized that with the current state of NLBs (which aren't suitable for replacing the Puppet-managed LBs at this point), having an instancepool for the infra nodes brings more issues than it solves.
This commit introduces a new variable `infra_use_instancepool` which defaults to `false` and must be set to `true` in addition to `use_instancepools = true` for the module to provision an instancepool for the infra nodes.
See also #98 
This is a breaking change for existing clusters which use `use_instancepools = true`.

Switch infra nodes to non-instancepool by default

---

lb.tf
variables.tf

We keep 20GB disks as the default to make the change non-breaking.
Requires https://github.com/appuio/terraform-modules/pull/62 to be released as v6.6.0.

Make LB disk size configurable
